### ISSUE TITLE
Typo In Blog 0001 Still Not Fixed

### ISSUE THREAD

**Issue by hihihioli** [wall03/wall03web#6]
![Screenshot 2023-10-27 at 10 24 00 AM](https://github.com/wall03/wall03web/assets/99088458/3eb1d43e-a4b8-4d7f-ab5c-9475a3216f40)

**Comment by hihihioli** [comment]
"added better **mobiel** support"
And no period.

**Comment by wall03** [comment]
this can be merged with other thread

**Comment by hihihioli** [comment]
i have no idea how github works
